### ISSUE TITLE
Cannot Get Multiple Permanent Discounts

### ISSUE THREAD

**Issue by cozyyyy** [DrexHD/VillagerFix#10]
I'm using version 1.4.2 of the mod on a 1.16.5 server.

When I tried curing villagers a second time, I was only given the temporary discount and not a permanent one (book costs were still -20 instead of -40). The server only runs the fabric api, lithium, phosphor, and this mod (as well as a vanillatweaks datapack).

Here's my config file (converted to a .txt since github doesn't support .json5), I only changed the chance of a villager to converting to a villagerzombie from -1 to 100, and everything else should be default:
[villagerfix.txt](https://github.com/DrexHD/VillagerFix/files/6368766/villagerfix.txt)

**Comment by DrexHD** [comment]
I can't replicate this behaviour, please make sure to update to the newest version and make sure it's actually caused by the mod (by removing it and verifying that it doesn't happen without it)!

**Comment by cozyyyy** [comment]
Hmm, so quick update: I found a warning when starting the server that said the villagerfix mod requires the modmenu mod, which I didn't have before now. After adding it and trying again I was able to get the second permanent discount (not sure that this is necessarily a cause and effect though, it's definitely possible the time I didn't get the permanent discount was just a fluke).
