### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by WarlordWossman** [DrexHD/VillagerFix#14]
Using latest version as of now (2.0.2) and crashing on startup, got a crashlog for now but if there is any additional tests etc. I am happy to cooperate!
[https://hastebin.com/humawelora.yaml](url)

**Comment by DrexHD** [comment]
Just uploaded a fix, should be available soon.

**Comment by WarlordWossman** [comment]
Hm, now I do not get a crashreport anymore but I still cannot launch the game:
https://hastebin.com/lininuhoti.kotlin

**Comment by DrexHD** [comment]
Please try the latest fix [download](https://github.com/DrexHD/VillagerFix/suites/2996542472/artifacts/67721083).
(Open the zip and use `villagerfix-2.0.3+1.17.jar`)

**Comment by WarlordWossman** [comment]
Yep that version definitely works!
Thanks for the quick fix.
