### ISSUE TITLE
Conversion chance config resulting into no zombie villagers

### ISSUE THREAD

**Issue by WarlordWossman** [DrexHD/VillagerFix#15]
On 2.0.3 the default config with the vanilla behavior (conversion chance -1) seems to work properly.
Unless I am misunderstanding the way to input the value 1.0 means they should always convert no matter if easy, normal or hard difficulty - what I found instead is that the value 1.0 behaved like a 0% chance, didn't even convert on hard when I tested!

**Comment by DrexHD** [comment]
You can check the value in-game using /vf. I am pretty sure you need to put 100 for 100% chance.

**Comment by WarlordWossman** [comment]
That could def explain it, I guess I was confused because it has -1.0 in there so I thought a probability of 1.0 would equal 100%!
Might want to add a comment about that to the config potentially.
