### ISSUE TITLE
Server Crash with just Fabric API and "Simple Voice Chat"

### ISSUE THREAD

**Issue by tateorrtot** [DrexHD/VillagerFix#17]
The server is just crashing with Fabric API and Simple Voice Chat. The server works fine when I take off the VillagerFix mod.

[crash.txt](https://github.com/DrexHD/VillagerFix/files/6706721/crash.txt)

**Comment by DrexHD** [comment]
I have just uploaded a fix on curseforge, can you check if that fixes your issue?
