### ISSUE TITLE
Incompatible with Sandwichable?

### ISSUE THREAD

**Issue by Leeo97one** [DrexHD/VillagerFix#2]
Not sure why but the game crashes right after I try to load or create a world when the two mods (VillagerFix and Sandwichable) are loaded.

Here is the crash-report : [crash-2020-09-28_21.37.31-client.txt](https://github.com/DrexHD/VillagerFix/files/5294734/crash-2020-09-28_21.37.31-client.txt)

**Comment by DrexHD** [comment]
Are you sure this is caused by VillagerFix (did you try the same mod list without villagerfix) ?

* I currently don't have time to look into it, but will once I do have the time for it.

**Comment by Leeo97one** [comment]
I'm not sure which mod is causing the crash, but I'm sure that the crash happens when the two mods are loaded together.
However, Sandwichable's dev said it's more likely to be an issue with the Cloth API.
https://github.com/FoundationGames/Sandwichable/issues/52#issuecomment-700867474
