### ISSUE TITLE
Breaks loading skins

### ISSUE THREAD

**Issue by MechanosG** [DrexHD/VillagerFix#3]
I'm not sure exactly how or why.  I'm assuming this mod somehow breaks net connectivity with the MC skin server or something.  But whenever I enable this mod, even when by itself, custom skins no longer load in Singleplayer or LAN.  Without this mod, they load fine.

MC 1.16.3
Fabric 0.6.1.51
Villager Fix 1.3.1
About 120 other mods

**Comment by DrexHD** [comment]
Version 1.4.0 should fix this 👍
