### ISSUE TITLE
Warning in logs during server startup

### ISSUE THREAD

**Issue by Romz24** [DrexHD/VillagerFix#5]
Every time I turn on the server, I see this warning in the console, and then also in the logs. Can you fix this?

```
 - Mod 'Villager Fix' (villagerfix) recommends version 1.14.6 or later of mod modmenu, which is missing!
	 - You must install version 1.14.6 or later of modmenu.
```

I use this mod only on the server side, and I see no reason to install modmenu on the server, as far as I know it is useless there.

**Comment by DrexHD** [comment]
Sorry for the late response, I removed this with the latest commit.
