### ISSUE TITLE
Blacklist not working for some items

### ISSUE THREAD

**Issue by DeropManz** [DrexHD/VillagerFix#6]
I blacklisted mutton and raw beef and they are still showing up in the butcher's trades. However, everything else seems to work fine.

**Comment by DrexHD** [comment]
Hi,
Can you please share your config? Also, note that blacklists will only work on new villagers and items need to be declared with their full identifier eg: minecraft:dirt.

**Comment by DeropManz** [comment]
{
	"features": {
		// The highest possible price discount a villager can give on it's default trade price (100 = vanilla, 0 = none)
		"max_discount": 100.0,
		// The highest possible price raise a villager can give on it's default trade price (100 = vanilla, 0 = none)
		"max_raise": 100.0,
		// Defines how high the max usages should be (100 = vanilla, 200 = 2 x more than vanilla)
		"max_uses": 110.0,
		// The chance of a villager to converting to a villagerzombie (-1 = vanilla behaviour)
		"conversion_chance": -1.0,
		// Whether or not villagers should be locked to a profession once they claim it (false = vanilla)
		"lock": false,
		// Blacklist trades (this only effects newly generated trades). Example value: ["minecraft:stick","minecraft:clay","minecraft:pumpkin"]
		"blacklisted_trades": [
			"minecraft:ender_pearl",
			"minecraft:cooked_rabbit",
			"minecraft:cooked_chicken",
			"minecraft:cooked_beef",
			"minecraft:beef",
			"minecraft:mutton",
			"minecraft:rabbit",
			"minecraft:chicken",
			"minecraft:diamond_boots",
			"minecraft:diamond_helmet",
			"minecraft:diamond_leggings",
			"minecraft:diamond_chestplate",
			"minecraft:diamond_sword",
			"minecraft:diamond_pickaxe",
			"minecraft:diamond_axe,",
			"minecraft:diamond_shovel",
			"minecraft:shield",
			"minecraft:book"
		]
	},
	"old_trades": {
		// Whether or not https://minecraft.gamepedia.com/Trading/Before_Village_%26_Pillage#Mechanics should be used for trade (un)locking
		"enabled": false,
		// The minimum amount of trades possible after which it can get locked (1.12 default: 2)
		"min_uses": 2,
		// The maximum amount of trades possible, if reached a trade is guaranteed to get locked (1.12 default: 12)
		"max_uses": 4,
		// The chance of a trade locking itself (1.12 default: 20)
		"lock_chance": 20.0,
		// The chance of a trade unlocking all other trades (1.12 default: 20)
		"unlock_chance": 20.0
	}
}

**Comment by DeropManz** [comment]
After more testing, it seems like Villagers who don't have any alternative trades ignore the blacklist. For example, if you blacklist ender pearls, villagers will only sell bottles.

**Comment by DrexHD** [comment]
I just uploaded a new version, which allows you to fully customize all kind of trades, so you can edit, add or remove any trades!

I hope this helps you ;)

**Comment by DeropManz** [comment]
Thank you
