### ISSUE TITLE
1.16.5 Crash on Startup

### ISSUE THREAD

**Issue by Slimation** [DrexHD/VillagerFix#9]
Sorry to bother you again, but when I use villagerfix-2.0.0+1.16.5.jar with only Fabric-api-0.32.9+1.16, and Fabric Loader 0.11.3-1.16.5 my game crashes on startup.

**Comment by DrexHD** [comment]
Can you check if this version works for you?
https://easyupload.io/ohfbw0

**Comment by Slimation** [comment]
Yep, it works, thanks a bunch!
